// Code generated by protoc-gen-go. DO NOT EDIT.
// source: play.proto

package play

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Step struct {
	X                    uint32   `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Player               *Player  `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_play_bc43de76e939773e, []int{0}
}
func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (dst *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(dst, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Step) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Step) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Player struct {
	Color                uint32   `protobuf:"varint,1,opt,name=color,proto3" json:"color,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_play_bc43de76e939773e, []int{1}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Player) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type State struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_play_bc43de76e939773e, []int{2}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *State) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*Step)(nil), "play.Step")
	proto.RegisterType((*Player)(nil), "play.Player")
	proto.RegisterType((*State)(nil), "play.State")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TurnClient is the client API for Turn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TurnClient interface {
	SetMove(ctx context.Context, in *Step, opts ...grpc.CallOption) (*State, error)
	GetMove(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Step, error)
	UpdateNext(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error)
	IsNextPlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*State, error)
	SetPlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*State, error)
	GetAIPlayer(ctx context.Context, in *State, opts ...grpc.CallOption) (*Player, error)
	HasChosen(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error)
	HasMoved(ctx context.Context, in *Player, opts ...grpc.CallOption) (*State, error)
	NewRoom(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error)
	GetID(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error)
}

type turnClient struct {
	cc *grpc.ClientConn
}

func NewTurnClient(cc *grpc.ClientConn) TurnClient {
	return &turnClient{cc}
}

func (c *turnClient) SetMove(ctx context.Context, in *Step, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/play.Turn/SetMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnClient) GetMove(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Step, error) {
	out := new(Step)
	err := c.cc.Invoke(ctx, "/play.Turn/GetMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnClient) UpdateNext(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/play.Turn/UpdateNext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnClient) IsNextPlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/play.Turn/IsNextPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnClient) SetPlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/play.Turn/SetPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnClient) GetAIPlayer(ctx context.Context, in *State, opts ...grpc.CallOption) (*Player, error) {
	out := new(Player)
	err := c.cc.Invoke(ctx, "/play.Turn/GetAIPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnClient) HasChosen(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/play.Turn/HasChosen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnClient) HasMoved(ctx context.Context, in *Player, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/play.Turn/HasMoved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnClient) NewRoom(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/play.Turn/NewRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnClient) GetID(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/play.Turn/GetID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TurnServer is the server API for Turn service.
type TurnServer interface {
	SetMove(context.Context, *Step) (*State, error)
	GetMove(context.Context, *Player) (*Step, error)
	UpdateNext(context.Context, *State) (*State, error)
	IsNextPlayer(context.Context, *Player) (*State, error)
	SetPlayer(context.Context, *Player) (*State, error)
	GetAIPlayer(context.Context, *State) (*Player, error)
	HasChosen(context.Context, *State) (*State, error)
	HasMoved(context.Context, *Player) (*State, error)
	NewRoom(context.Context, *State) (*State, error)
	GetID(context.Context, *State) (*State, error)
}

func RegisterTurnServer(s *grpc.Server, srv TurnServer) {
	s.RegisterService(&_Turn_serviceDesc, srv)
}

func _Turn_SetMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Step)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).SetMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/SetMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).SetMove(ctx, req.(*Step))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turn_GetMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).GetMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/GetMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).GetMove(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turn_UpdateNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(State)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).UpdateNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/UpdateNext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).UpdateNext(ctx, req.(*State))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turn_IsNextPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).IsNextPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/IsNextPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).IsNextPlayer(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turn_SetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).SetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/SetPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).SetPlayer(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turn_GetAIPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(State)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).GetAIPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/GetAIPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).GetAIPlayer(ctx, req.(*State))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turn_HasChosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(State)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).HasChosen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/HasChosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).HasChosen(ctx, req.(*State))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turn_HasMoved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).HasMoved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/HasMoved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).HasMoved(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turn_NewRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(State)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).NewRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/NewRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).NewRoom(ctx, req.(*State))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turn_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(State)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Turn/GetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServer).GetID(ctx, req.(*State))
	}
	return interceptor(ctx, in, info, handler)
}

var _Turn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "play.Turn",
	HandlerType: (*TurnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMove",
			Handler:    _Turn_SetMove_Handler,
		},
		{
			MethodName: "GetMove",
			Handler:    _Turn_GetMove_Handler,
		},
		{
			MethodName: "UpdateNext",
			Handler:    _Turn_UpdateNext_Handler,
		},
		{
			MethodName: "IsNextPlayer",
			Handler:    _Turn_IsNextPlayer_Handler,
		},
		{
			MethodName: "SetPlayer",
			Handler:    _Turn_SetPlayer_Handler,
		},
		{
			MethodName: "GetAIPlayer",
			Handler:    _Turn_GetAIPlayer_Handler,
		},
		{
			MethodName: "HasChosen",
			Handler:    _Turn_HasChosen_Handler,
		},
		{
			MethodName: "HasMoved",
			Handler:    _Turn_HasMoved_Handler,
		},
		{
			MethodName: "NewRoom",
			Handler:    _Turn_NewRoom_Handler,
		},
		{
			MethodName: "GetID",
			Handler:    _Turn_GetID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "play.proto",
}

func init() { proto.RegisterFile("play.proto", fileDescriptor_play_bc43de76e939773e) }

var fileDescriptor_play_bc43de76e939773e = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x9b, 0xfe, 0xa4, 0xed, 0x69, 0xbf, 0x6f, 0x71, 0x10, 0x29, 0x5d, 0x95, 0xb1, 0xa5,
	0x41, 0xa1, 0x42, 0xbd, 0x02, 0x31, 0x90, 0x64, 0x61, 0x91, 0x44, 0x2f, 0x60, 0xb4, 0x07, 0x5c,
	0xd4, 0x4e, 0xc8, 0x9c, 0x6a, 0x72, 0x33, 0x5e, 0xab, 0x4c, 0x32, 0x42, 0x93, 0x45, 0x70, 0x37,
	0xef, 0xe4, 0x39, 0x4f, 0xde, 0x03, 0x03, 0x90, 0x1e, 0x64, 0xb1, 0x49, 0x33, 0xc5, 0x0a, 0xfb,
	0xe6, 0x2c, 0x42, 0xe8, 0x27, 0x4c, 0x29, 0x4e, 0xc1, 0xc9, 0x67, 0xce, 0xc2, 0xf1, 0xfe, 0xc5,
	0x4e, 0x6e, 0x52, 0x31, 0xeb, 0x56, 0xa9, 0xc0, 0x25, 0xb8, 0x86, 0xa5, 0x6c, 0xd6, 0x5b, 0x38,
	0xde, 0x64, 0x3b, 0xdd, 0x94, 0x9a, 0xa7, 0xf2, 0x2e, 0xb6, 0xdf, 0xc4, 0x06, 0xdc, 0xea, 0x06,
	0x2f, 0x60, 0xf0, 0xa6, 0x0e, 0x2a, 0xb3, 0xbe, 0x2a, 0xe0, 0x7f, 0xe8, 0x46, 0x7e, 0x29, 0x1d,
	0xc7, 0xdd, 0xc8, 0x17, 0xb7, 0x30, 0x48, 0x58, 0x32, 0xe1, 0x25, 0xb8, 0x9a, 0x25, 0x9f, 0x74,
	0xc9, 0x8f, 0x62, 0x9b, 0x9a, 0x03, 0xdb, 0xef, 0x1e, 0xf4, 0x9f, 0x4f, 0xd9, 0x11, 0x97, 0x30,
	0x4c, 0x88, 0x1f, 0xd5, 0x27, 0x21, 0x54, 0x55, 0xcc, 0x0a, 0xf3, 0xc9, 0xef, 0x59, 0x32, 0x89,
	0x0e, 0xae, 0x60, 0x18, 0x58, 0xaa, 0x56, 0x78, 0x7e, 0x36, 0x23, 0x3a, 0xe8, 0x01, 0xbc, 0xa4,
	0x7b, 0xc9, 0xb4, 0xa3, 0x9c, 0xf1, 0xdc, 0xd1, 0x14, 0xde, 0xc0, 0x34, 0xd2, 0x86, 0xb2, 0x6b,
	0xd6, 0xad, 0x0d, 0xd8, 0x83, 0x71, 0x42, 0x7f, 0x22, 0xaf, 0x61, 0x12, 0x10, 0xdf, 0x47, 0x96,
	0xad, 0x35, 0xa8, 0x0d, 0x8a, 0x0e, 0xae, 0x61, 0x1c, 0x4a, 0xfd, 0xf0, 0xae, 0x34, 0x1d, 0x5b,
	0xbb, 0xae, 0x61, 0x14, 0x4a, 0x6d, 0x96, 0xdf, 0xb7, 0xff, 0x7d, 0x05, 0xc3, 0x1d, 0x7d, 0xc5,
	0x4a, 0x7d, 0xb4, 0xfa, 0xae, 0x60, 0x10, 0x10, 0x47, 0x7e, 0x1b, 0xf4, 0xea, 0x96, 0x0f, 0xeb,
	0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0x58, 0xcd, 0xa4, 0x42, 0x66, 0x02, 0x00, 0x00,
}
